### ISSUE TITLE
Differences in notable times

### ISSUE THREAD

**Issue by dangerden** [peakvisor/skygazing#1]
These two methods calculate significantly different sunrise times:

```
auto suntimes = Sky::getTimes<Sun>(now, toCoordinates(center));
auto sunrise = Sky::getTodaysRiseUTC<Sun>(now, toCoordinates(center));
```

getTimes<Sun>                 => 1658238390
getTodaysRiseUTC<Sun> => 1658233834

**Comment by eofom** [comment]
One of those was from the older version of the library. In the current version, use
```Sky::getNotableTimes(UTC utc, const DegreesCoordinates &observer) ```
