### ISSUE TITLE
Moon location issue

### ISSUE THREAD

**Issue by dangerden** [peakvisor/skygazing#2]
Here's a screenshot with the problem taken in the PeakVisor app (iOS)
![IMG_8714](https://user-images.githubusercontent.com/1210302/184584427-1a8439b9-66a4-47d0-9cfd-5810faf8f4b8.PNG)

There's a vertical difference in the projected Moon location.

Here're [images](https://www.dropbox.com/sh/yf4ck8d6rcy2li7/AAC5n5xVLPvqCmCGziN_6Fb_a?dl=0) to debug the issue. It might be related to iOS app using an outdated version of the library or it using the wrong interface. Either way it should be solved.

**Comment by eofom** [comment]
Yes, iOS app was using an outdated version of the library. Also, celestial objects distance is now counted from the observer. To get the distance from the Earth center, use
```CelestialObjectObservation::geocentricDistance```

**Comment by dangerden** [comment]
@eofom it seems like a podspec was added like a part of the fix? it might be useful to register it to make it easily available to others.
